export * from './Auth/Login'
export * from './Auth/Register'
export * from './Home/Home'
export * from './EditProfile/EditProfile'
export * from './Profile/Profile'
export * from './Photo/Photo'
export * from './Search/Search'
